// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElImg: typeof import('element-plus/es')['ElImg']
  const ElLink: typeof import('element-plus/es')['ElLink']
  const ElRow: typeof import('element-plus/es')['ElRow']
}
export {}
